### ISSUE TITLE
CORS error for video thumbnail

### ISSUE THREAD

**Issue by crazykalp** [vbrick/rev-sdk-js#64]
Note: All Vbrick APIS are working fine, only thumbnail redirected URL throws CORS error

when trying to call image thumbnail api

GET API

https://mbf.rev.vbrick.com/api/v2/videos/a1b64536-bfa0-4d85-8a89-086962d5c79e/thumbnail

this API redirects to 302 to 

https://media.us.vbrickrev.com/86b01a64-31b4-40b9-a9a5-b1d7c0d1ad70/53d190e8-c9b9-47dd-9b10-304c791137b6.jpg?Expires=1664815520&Signature=B68edBD-ZQ5aVc96Scb8eR6oMAlvDLU8bdmMDAJLZJ6mc7T3vGVzfGRroSN-DfkLrwoyfUqXpDUL25YiibIS~pPoJz4vbGs6jaiOiQO~PFc9rd7zdZJPGq8AohfcLuYA537jhIKkC8jalilxK1svoXDoPL7rjcIJFG3crDEu8Stxrf8PVB7qh1Gsd3~14YaCTWhwZvfRImOWHIXSHFo~T1BhXRHyHvPTXrqtSDiigxPYwSNvrGKF4~gUGx0X3UCqlVw8zgJjzLA-u0TEmSUoxUSKuejsYOg2wWQMF49VC85NQumNzJ2R9yLS9~vzqz09N~-ShDjhisnmiNswLYlgNA__&Key-Pair-Id=APKAJAJQHUPMKAB67DRQ

This 302 redirected API throws CORS error

Can you please help on it ?
![image](https://user-images.githubusercontent.com/109093673/193632324-4980bcfc-267d-48b5-bbd5-5eba830d5e3d.png)

Note: All Vbrick APIS are working fine, only thumbnail redirected URL throws cors error

**Comment by crazykalp** [comment]
Hi ,

Could you please look into this ?

**Comment by lukeselden** [comment]
Hi @crazykalp  - the CORS settings for the redirected media URL *should* follow the CORS settings for your account - so if you have CORS enabled then the thumbnail should work on those domains you have in your allow list (or `*` if configured).

I've created a Vbrick Support ticket on your behalf to discuss further. In the future (for fastest response times) I recommend opening a support ticket rather than a github issue, unless the behavior relates to a bug in the rev-sdk code itself.
